# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stratux ADS-B
subtitle: DIY/Low-cost Portable ADS-B
description: >- # this means to ignore newlines until "baseurl:"
  Stratux ADS-B receiver software for pilots.
author: cyoung
email: website@stratux.me
avatar: assets/images/logo.png

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
#TESTING:
url: "http://stratux.me"
#url: "http://updates.stratux.me:4000" # the base hostname & protocol for your site

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics: G-FYVQ8XFNLN

# Google tag manager
#google:
#  tag_manager:
#    container_id: G-FYVQ8XFNLN

# The following settings are NECESSARY for the Prologue theme to run:
#TESTING:
remote_theme: chrisbobbe/jekyll-theme-prologue
#theme: jekyll-theme-prologue
collections: [sections]

url: "http://stratux.me" # the base hostname & protocol for your site


plugins:
  - jemoji
  - jekyll-sitemap
